# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./src/Model/Undo/PathwayMemento.h \
    ./src/Test/UnitTests.h \
    ./src/View/Overlay.h \
    ./src/View/VTK/vtkOpenGLImageOverlayActor.h \
    ./src/View/VTK/vtkROI.h \
    ./src/WITUtils.h \
    ./src/WITTypedefs.h \
    ./src/Model/Undo/CompleteMemento.h \
    ./src/Model/Undo/Memento.h \
    ./src/Model/Undo/VOICollectionMemento.h \
    ./src/Model/Undo/VOIMemento.h \
    ./src/View/VTK/vtkFilledCaptionActor2D.h \
    ./src/Model/WITPathwayViz.h \
    ./src/WITApplication.h \
    ./src/View/Qt/QuadSplitter.h \
    ./src/View/WITMainWindow.h \
    ./src/View/Qt/QuadSplitterHandle.h \
    ./src/Controller/PathwayController.h \
    ./src/Controller/WITMainWindowController.h \
    ./src/Controller/SubjectDataController.h \
    ./src/View/WITVolumeViz.h \
    ./src/Controller/vtkInteractorStyleWIT.h \
    ./src/Controller/WITGestureController.h \
    ./src/View/WITToolPanel.h \
    ./src/View/WITGroupButton.h \
    ./src/View/WITGroupPanel.h \
    ./src/View/WITStatsPanel.h \
    ./src/View/WITVOIPanel.h \
    ./src/View/Qt/QuadSplit.h \
    ./src/Controller/WITFrameController.h \
    ./src/Controller/WITGroupPanelController.h \
    ./src/Model/Undo/UndoSystem.h \
    ./src/View/WITFrame.h
SOURCES += ./src/Controller/PathwayController.cpp \
    ./src/Controller/SubjectDataController.cpp \
    ./src/Controller/WITFrameController.cpp \
    ./src/Controller/WITGestureController.cpp \
    ./src/Controller/WITGroupPanelController.cpp \
    ./src/Controller/WITMainWindowController.cpp \
    ./src/main.cpp \
    ./src/Model/Undo/CompleteMemento.cpp \
    ./src/Model/Undo/PathwayMemento.cpp \
    ./src/Model/Undo/UndoSystem.cpp \
    ./src/View/Overlay.cpp \
    ./src/View/VTK/vtkOpenGLImageOverlayActor.cpp \
    ./src/View/VTK/vtkROI.cpp \
    ./src/View/VTK/vtkFilledCaptionActor2D.cpp \
    ./src/Controller/vtkInteractorStyleWIT.cpp \
    ./src/Model/WITPathwayViz.cpp \
    ./src/View/WITVolumeViz.cpp \
    ./src/WITApplication.cpp \
    ./src/View/Qt/QuadSplit.cpp \
    ./src/View/Qt/QuadSplitter.cpp \
    ./src/View/Qt/QuadSplitterHandle.cpp \
    ./src/View/WITFrame.cpp \
    ./src/View/WITGroupButton.cpp \
    ./src/View/WITGroupPanel.cpp \
    ./src/View/WITMainWindow.cpp \
    ./src/View/WITToolPanel.cpp
