/*
    File:       Controller/EventInterpreter.h
    Summary:    Receives events generated by controllers and gives each event access
                to the underlying model.
*/

#ifndef EVENT_INTERPRETER_H
#define EVENT_INTERPRETER_H

class EventInterpreter
{
};

#endif