#ifndef MEMENTO_H
#define MEMENTO_H
#include <QObject>
#include <iostream>
/**
	Memento the an abstract base class for specific Memento implementations.
	The undo system uses mementos to keep a history of the state of the application.
	Each Memento type stores the state of a specific component of the application and
	they are generated by the component's model.  Mementos can be stored to a stream
	and restored from a stream.

	@author Doug Hamilton
*/
class Memento
{
public:

	virtual void Undo(){}
	virtual void Redo(){}
	
};

#endif