#ifndef MEMENTO_H
#define MEMENTO_H

#include <iostream>
/**
	Memento the an abstract base class for specific Memento implementations.
	The undo system uses mementos to keep a history of the state of the application.
	Each Memento type stores the state of a specific component of the application and
	they are generated by the component's model.  Mementos can be stored to a stream
	and restored from a stream.

	@author Doug Hamilton
*/
class Memento
{
public:
	/**
		Base constructor, does nothing.
	*/
	Memento(){}

	/**
		Constructor for restoring a memento from a stream
	*/
	Memento(std::istream stream);

	/**
		Writes the memento to a stream
	*/
	virtual void toStream(std::ostream stream) = 0;
	
};

#endif